---
modelog: debug

http:
  type: port
  bind_ip: 0.0.0.0
  port: :8081

postgressdb:
  host: postgres-instance
  port: 5432
  user: admin
  name: admin
  password: admin
  database: orders

nats:
  clusterid: order-nats
  clientid: order-publisher
  url: nats-streaming-instance:4222
  channel: order-channel